server.port=8080
spring.datasource.url=jdbc:h2:mem:campaigndb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop

app.cors.allowed-origins=http://localhost:5173